language: java
sudo: false
jdk:
    - openjdk9
    - openjdk10
    - openjdk11
env:
    - NODE_VERSION=8 CC=clang CXX=clang++
    - NODE_VERSION=10 CC=clang CXX=clang++
#    - NODE_VERSION=12 CC=clang CXX=clang++
before_install:
    - nvm install $NODE_VERSION
before_script:
    - npm install
script:
    - npm test
